name: Build-ACR-Solution

on: 
  push:
    paths-ignore:
      - '**.md'
jobs:
  Build-API-Solution:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ACR build
        id: acr
        uses: azure/acr-build@v1
        with:
          service_principal: ${{ secrets.service_principal_id }}
          service_principal_password: ${{ secrets.service_principal_password }}
          tenant: ${{ secrets.tenant }}
          registry: ${{ secrets.registry }}
          repository: ${{ secrets.dotnet }}
          image: image
          git_access_token: ${{ secrets.git_access_token }}
          folder: _TheApplication/Source/API\
          dockerfile: _TheApplication\Source\API\DockerFile
          branch: master
          build_args: ''