name: Build-Coding-Solution

on: [push]

jobs:
  Build-Coding-Solution:

    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['6.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Install dependencies
        run: dotnet restore .\Source\API
      - name: Build
        run: dotnet build .\Source\API --configuration Release --no-restore
      - name: Test
        run: dotnet build .\Source\API --no-restore --verbosity normal