apiVersion: v1
kind: Service
metadata:
  name: react-ui
  labels:
    app: react-ui
    service: react-ui
spec:
  ports:
    - port: 8081
      targetPort: 3000
      protocol: TCP
  type: LoadBalancer
  selector:
    service: react-ui
