$schema: https://azuremlschemas.azureedge.net/latest/batchDeployment.schema.json
name: linreg-batch-deployment
endpoint_name: linear-regression-batch-endpoint
model: azureml:linear-regression-model@latest
code_configuration:
  code: ../src
  scoring_script: score.py
environment: azureml:linear-regression-env@latest
compute: azureml:cpu-cluster
resources:
  instance_count: 1
max_concurrency_per_instance: 1
mini_batch_size: 1
output_action: append_row
output_file_name: predictions.csv
retry_settings:
  max_retries: 1
  timeout: 300
error_threshold: -1
logging_level: info
